### ISSUE TITLE
feat : 로그인 화면 UI

### ISSUE THREAD

**Issue by hyewon3938** [4INCENSE/issue-tracker-frontend#2]
### 로그인 전 사이트 첫 화면

- [x] 메인 배경화면
- [x] 로고 애니메이션
- [x] SNS 로그인 폼
- [x] 반응형

**Comment by hyewon3938** [comment]
### 완성된 로그인 화면 UI

![로그인컴포넌트](https://user-images.githubusercontent.com/58355499/109299480-86541c80-7878-11eb-9aa3-a53e39f95e05.gif)

최대한 간단하고 심플하게 만들었다.

**Comment by beemiel** [comment]
귀욥다

**Comment by hyewon3938** [comment]
## 반응형 로그인 화면 UI

### 반응형
![로그인반응형](https://user-images.githubusercontent.com/58355499/109396944-72dbab00-7977-11eb-86d7-dfc5df627a19.gif)

### 가로반응형
![로그인가로반응형](https://user-images.githubusercontent.com/58355499/109396925-58093680-7977-11eb-8535-8e46ba96cc56.gif)

### 세로반응형
![로그인세로반응형](https://user-images.githubusercontent.com/58355499/109396927-5b042700-7977-11eb-81e7-a01bee1c4a1f.gif)

### 모바일

![bandicam 2021-02-28 04-05-42-046](https://user-images.githubusercontent.com/58355499/109397518-4d9c6c00-797a-11eb-9296-fcd166b87f8e.jpg)
>

**Comment by hyewon3938** [comment]
## 반응형 로그인 화면 UI

### - 반응형

![반응형](https://user-images.githubusercontent.com/58355499/109398592-38770b80-7981-11eb-8bf0-7efb0994abf5.gif)

### - 모바일

![모바일](https://user-images.githubusercontent.com/58355499/109398546-e59d5400-7980-11eb-83a8-dea8bb7a37f9.jpg)
